// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4X-o9v3Gf509eHUgt622vi8ryVi3kWTs',
    appId: '1:578503926545:web:0310344fd66cb5b7f0e2b0',
    messagingSenderId: '578503926545',
    projectId: 'gpstracker-891e2',
    authDomain: 'gpstracker-891e2.firebaseapp.com',
    storageBucket: 'gpstracker-891e2.appspot.com',
    measurementId: 'G-E985Q99FRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6d-tGYQiC6-GSIv-sdml-P6HWCzWdxqU',
    appId: '1:578503926545:android:6d13469b588efa3af0e2b0',
    messagingSenderId: '578503926545',
    projectId: 'gpstracker-891e2',
    storageBucket: 'gpstracker-891e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GQWekW-bGYT8N2r-bAsy8YoPkTEXMR0',
    appId: '1:578503926545:ios:5b6cf64aeca31f97f0e2b0',
    messagingSenderId: '578503926545',
    projectId: 'gpstracker-891e2',
    storageBucket: 'gpstracker-891e2.appspot.com',
    iosClientId: '578503926545-6rbjiqpd3ujsmg9lf12666cm8qvck6q8.apps.googleusercontent.com',
    iosBundleId: 'com.next.cargpstracker',
  );
}
