import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          'App_Name': 'GPS Tracker',
          'Login': 'Login',
          'Registration': 'Registeration',
          'Save': 'Save',
          'Live': 'Live',
          'History': 'History',
          'Setting': 'Settings',
          'Apply': 'Apply',
          'Training': 'Training Mode',
          'alert-title': 'Switch On/Off Alert',
          "device-serial": "device serial",
          "device": "device",
          "change_lang": "change lang",
          "sending-varify-code": "sending code success",
          "add-user-msg": "your phone number registered",
          "device-sim-num": "Device sim card number",
          "Logout": "Logout",
          "Plus": "Plus",
          "car": "Car",
          "motor": "Motor",
          "truck": "Truck",
          "username": "User Name",
          "phone": "Phone Number",
          "email": "Email Address",
          "country": "Country Name",
          "city": "City Name",

        },
        'fa_IR': {
          'App_Name': 'موقعیت یاب',
          'Login': 'ورود',
          'Registration': 'ثبت نام',
          'Save': 'ذخیره',
          'Live': 'زنده',
          'History': 'تاریخچه',
          'Setting': 'تنظیمات',
          'Apply': 'قبول',
          'Training': 'نسخه آزمایش',
          'alert-title': 'هشدار خاموش کردن',
          "device-serial": "سریال دستگاه",
          "device": "دستگاه",
          "change_lang": "تغییر زبان",
          "sending-varify-code": "کد مورد نظر ارسال شد",
          "add-user-msg": "موبایل شما در سامانه ثبت شد",
          "device-sim-num": "شماره سیم کارت دستگاه ",
          "Logout": "خروج",
          "Plus": "پلاس",
          "car": "خودروی سواری",
          "motor": "موتور سیکلت",
          "truck": "خودروی سنگین",
          "username": "نام کاربری",
          "phone": "شماره تماس",
          "email": "آدرس ایمیل",
          "country": "نام کشور",
          "city": "نام شهر",
        },
      };
}
